"""
Price & Production History Screen
Allows users to select a crop and a date, view actual price and production for that date,
and see next-week predictions generated by the ML models.
"""

from datetime import date
from kivy.lang import Builder
from kivy.metrics import dp
from kivy.properties import StringProperty
from kivy.uix.screenmanager import Screen
from kivymd.app import MDApp
from kivymd.uix.button import MDRaisedButton, MDIconButton, MDFlatButton
from kivymd.uix.card import MDCard
from kivymd.uix.dialog import MDDialog
from kivymd.uix.menu import MDDropdownMenu
from kivymd.uix.label import MDLabel
from kivymd.uix.pickers import MDDatePicker

from database.data_service import (
    get_all_crops,
    get_price_by_date,
    get_production_by_date,
    get_region_district,
)
from utils.ml_engine import predict_price, predict_production
from utils.layout_helpers import show_snackbar


KV = """
<PriceProductionHistoryScreen>:
    name: "price_history"
    canvas.before:
        Color:
            rgba: 0.96, 0.98, 0.96, 1
        Rectangle:
            pos: self.pos
            size: self.size

    MDBoxLayout:
        orientation: "vertical"

        # Top Bar Navigation
        MDBoxLayout:
            size_hint_y: None
            height: dp(54)
            padding: dp(12), dp(4)
            spacing: dp(8)
            md_bg_color: 1, 1, 1, 1

            MDIconButton:
                icon: "arrow-left"
                theme_text_color: "Custom"
                text_color: 0.22, 0.55, 0.25, 1
                pos_hint: {"center_y": 0.5}
                on_release: root.go_back()

            MDLabel:
                text: "Price & Production History"
                font_style: "Subtitle1"
                bold: True
                theme_text_color: "Custom"
                text_color: 0.12, 0.28, 0.14, 1
                pos_hint: {"center_y": 0.5}

        ScrollView:
            MDBoxLayout:
                orientation: "vertical"
                padding: dp(16), dp(16), dp(16), dp(24)
                spacing: dp(16)
                size_hint_y: None
                height: self.minimum_height

                # Card 1: Selection Controls
                MDCard:
                    orientation: "vertical"
                    size_hint_y: None
                    height: self.minimum_height
                    radius: [16, 16, 16, 16]
                    elevation: 1
                    padding: dp(16)
                    spacing: dp(12)
                    md_bg_color: 1, 1, 1, 1

                    MDLabel:
                        text: "Search by Crop & Date"
                        font_style: "Subtitle1"
                        bold: True
                        theme_text_color: "Custom"
                        text_color: 0.15, 0.45, 0.20, 1
                        size_hint_y: None
                        height: dp(24)

                    MDLabel:
                        text: "Select a crop and date to inspect actual market records and view AI forecasts for the next week."
                        font_style: "Caption"
                        theme_text_color: "Custom"
                        text_color: 0.45, 0.45, 0.45, 1
                        size_hint_y: None
                        height: self.texture_size[1]

                    # Crop selector button
                    MDBoxLayout:
                        orientation: "horizontal"
                        size_hint_y: None
                        height: dp(44)
                        spacing: dp(8)

                        MDIconButton:
                            icon: "sprout"
                            theme_text_color: "Custom"
                            text_color: 0.25, 0.62, 0.30, 1
                            pos_hint: {"center_y": 0.5}

                        MDRaisedButton:
                            id: crop_btn
                            text: root.selected_crop_name or "Select Crop"
                            font_style: "Button"
                            size_hint_x: 1
                            elevation: 0
                            md_bg_color: 0.90, 0.95, 0.90, 1
                            text_color: 0.15, 0.45, 0.20, 1
                            on_release: root.open_crop_menu()

                    # Date selector button
                    MDBoxLayout:
                        orientation: "horizontal"
                        size_hint_y: None
                        height: dp(44)
                        spacing: dp(8)

                        MDIconButton:
                            icon: "calendar-month"
                            theme_text_color: "Custom"
                            text_color: 0.25, 0.62, 0.30, 1
                            pos_hint: {"center_y": 0.5}

                        MDRaisedButton:
                            id: date_btn
                            text: root.selected_date_str or "Select Date"
                            font_style: "Button"
                            size_hint_x: 1
                            elevation: 0
                            md_bg_color: 0.90, 0.95, 0.90, 1
                            text_color: 0.15, 0.45, 0.20, 1
                            on_release: root.show_date_picker()

                    MDRaisedButton:
                        text: "SEARCH & PREDICT"
                        bold: True
                        size_hint_x: 1
                        height: dp(44)
                        elevation: 1
                        md_bg_color: 0.25, 0.62, 0.30, 1
                        on_release: root.load_data()

                # Card 2: Actual Market Data Card
                MDCard:
                    id: actual_card
                    orientation: "vertical"
                    size_hint_y: None
                    height: self.minimum_height
                    radius: [16, 16, 16, 16]
                    elevation: 1
                    padding: dp(16)
                    spacing: dp(10)
                    md_bg_color: 1, 1, 1, 1

                    MDBoxLayout:
                        orientation: "horizontal"
                        size_hint_y: None
                        height: dp(26)
                        spacing: dp(8)

                        MDIconButton:
                            icon: "database-check"
                            theme_text_color: "Custom"
                            text_color: 0.22, 0.55, 0.25, 1
                            size_hint: None, None
                            size: dp(24), dp(24)
                            pos_hint: {"center_y": 0.5}

                        MDLabel:
                            text: "Actual Market Data"
                            font_style: "Subtitle1"
                            bold: True
                            theme_text_color: "Custom"
                            text_color: 0.15, 0.40, 0.18, 1
                            pos_hint: {"center_y": 0.5}

                    MDLabel:
                        id: actual_date_lbl
                        text: "Date: -"
                        font_style: "Caption"
                        theme_text_color: "Custom"
                        text_color: 0.45, 0.45, 0.45, 1
                        size_hint_y: None
                        height: dp(18)

                    # Price sub-card
                    MDCard:
                        size_hint_y: None
                        height: dp(60)
                        radius: [12, 12, 12, 12]
                        elevation: 0
                        md_bg_color: 0.94, 0.98, 0.94, 1
                        padding: dp(12), dp(8)

                        MDBoxLayout:
                            orientation: "horizontal"
                            spacing: dp(10)

                            MDIconButton:
                                icon: "cash-multiple"
                                theme_text_color: "Custom"
                                text_color: 0.20, 0.55, 0.25, 1
                                pos_hint: {"center_y": 0.5}

                            MDBoxLayout:
                                orientation: "vertical"
                                pos_hint: {"center_y": 0.5}

                                MDLabel:
                                    text: "Actual Price"
                                    font_style: "Caption"
                                    theme_text_color: "Custom"
                                    text_color: 0.40, 0.40, 0.40, 1

                                MDLabel:
                                    id: actual_price_label
                                    text: "Select crop & date to search"
                                    font_style: "Subtitle2"
                                    bold: True
                                    theme_text_color: "Custom"
                                    text_color: 0.15, 0.45, 0.20, 1

                    # Production sub-card
                    MDCard:
                        size_hint_y: None
                        height: dp(60)
                        radius: [12, 12, 12, 12]
                        elevation: 0
                        md_bg_color: 0.94, 0.98, 0.94, 1
                        padding: dp(12), dp(8)

                        MDBoxLayout:
                            orientation: "horizontal"
                            spacing: dp(10)

                            MDIconButton:
                                icon: "scale"
                                theme_text_color: "Custom"
                                text_color: 0.20, 0.55, 0.25, 1
                                pos_hint: {"center_y": 0.5}

                            MDBoxLayout:
                                orientation: "vertical"
                                pos_hint: {"center_y": 0.5}

                                MDLabel:
                                    text: "Actual Production"
                                    font_style: "Caption"
                                    theme_text_color: "Custom"
                                    text_color: 0.40, 0.40, 0.40, 1

                                MDLabel:
                                    id: actual_prod_label
                                    text: "Select crop & date to search"
                                    font_style: "Subtitle2"
                                    bold: True
                                    theme_text_color: "Custom"
                                    text_color: 0.15, 0.45, 0.20, 1

                # Card 3: Next Week AI Predictions Card
                MDCard:
                    id: pred_card
                    orientation: "vertical"
                    size_hint_y: None
                    height: self.minimum_height
                    radius: [16, 16, 16, 16]
                    elevation: 1
                    padding: dp(16)
                    spacing: dp(10)
                    md_bg_color: 1, 1, 1, 1

                    MDBoxLayout:
                        orientation: "horizontal"
                        size_hint_y: None
                        height: dp(26)
                        spacing: dp(8)

                        MDIconButton:
                            icon: "chart-timeline-variant-shimmer"
                            theme_text_color: "Custom"
                            text_color: 0.15, 0.40, 0.70, 1
                            size_hint: None, None
                            size: dp(24), dp(24)
                            pos_hint: {"center_y": 0.5}

                        MDLabel:
                            text: "Next-Week AI Predictions"
                            font_style: "Subtitle1"
                            bold: True
                            theme_text_color: "Custom"
                            text_color: 0.10, 0.30, 0.55, 1
                            pos_hint: {"center_y": 0.5}

                    MDLabel:
                        id: pred_district_lbl
                        text: "Model: LSTM Price & RF Production"
                        font_style: "Caption"
                        theme_text_color: "Custom"
                        text_color: 0.45, 0.45, 0.45, 1
                        size_hint_y: None
                        height: dp(18)

                    # Predicted Price sub-card
                    MDCard:
                        size_hint_y: None
                        height: dp(60)
                        radius: [12, 12, 12, 12]
                        elevation: 0
                        md_bg_color: 0.92, 0.96, 1.0, 1
                        padding: dp(12), dp(8)

                        MDBoxLayout:
                            orientation: "horizontal"
                            spacing: dp(10)

                            MDIconButton:
                                icon: "trending-up"
                                theme_text_color: "Custom"
                                text_color: 0.15, 0.40, 0.75, 1
                                pos_hint: {"center_y": 0.5}

                            MDBoxLayout:
                                orientation: "vertical"
                                pos_hint: {"center_y": 0.5}

                                MDLabel:
                                    text: "Predicted Price (Next Week)"
                                    font_style: "Caption"
                                    theme_text_color: "Custom"
                                    text_color: 0.35, 0.40, 0.50, 1

                                MDLabel:
                                    id: pred_price_label
                                    text: "-"
                                    font_style: "Subtitle2"
                                    bold: True
                                    theme_text_color: "Custom"
                                    text_color: 0.10, 0.30, 0.65, 1

                    # Predicted Production sub-card
                    MDCard:
                        size_hint_y: None
                        height: dp(60)
                        radius: [12, 12, 12, 12]
                        elevation: 0
                        md_bg_color: 0.92, 0.96, 1.0, 1
                        padding: dp(12), dp(8)

                        MDBoxLayout:
                            orientation: "horizontal"
                            spacing: dp(10)

                            MDIconButton:
                                icon: "chart-bar"
                                theme_text_color: "Custom"
                                text_color: 0.15, 0.40, 0.75, 1
                                pos_hint: {"center_y": 0.5}

                            MDBoxLayout:
                                orientation: "vertical"
                                pos_hint: {"center_y": 0.5}

                                MDLabel:
                                    text: "Predicted Production (Next Week)"
                                    font_style: "Caption"
                                    theme_text_color: "Custom"
                                    text_color: 0.35, 0.40, 0.50, 1

                                MDLabel:
                                    id: pred_prod_label
                                    text: "-"
                                    font_style: "Subtitle2"
                                    bold: True
                                    theme_text_color: "Custom"
                                    text_color: 0.10, 0.30, 0.65, 1
"""

Builder.load_string(KV)


class PriceProductionHistoryScreen(Screen):
    selected_crop_id = None
    selected_crop_name = StringProperty()
    selected_date = None
    selected_date_str = StringProperty()
    _menu = None
    crops = []

    def on_pre_enter(self, *args):
        # Pre-populate crops if not loaded
        if not self.crops:
            self.crops = [(cid, name) for cid, name in get_all_crops()]
        if self.crops and not self.selected_crop_id:
            self.selected_crop_id, self.selected_crop_name = self.crops[0]
        # Pre-populate default date if none chosen (e.g. today or 2026-08-05)
        if not self.selected_date:
            self.selected_date = date.today()
            self.selected_date_str = self.selected_date.strftime("%d %b %Y")

    def go_back(self):
        if self.manager:
            self.manager.transition.direction = "right"
            self.manager.current = "dashboard"

    def open_crop_menu(self):
        if not self.crops:
            self.crops = [(cid, name) for cid, name in get_all_crops()]
        menu_items = [
            {
                "viewclass": "OneLineListItem",
                "text": name,
                "height": dp(48),
                "on_release": lambda y=cid, x=name: self.select_crop(y, x),
            }
            for cid, name in self.crops
        ]
        if self._menu:
            self._menu.dismiss()
        self._menu = MDDropdownMenu(
            caller=self.ids.crop_btn,
            items=menu_items,
            width_mult=4,
        )
        self._menu.open()

    def select_crop(self, crop_id, crop_name):
        self.selected_crop_id = crop_id
        self.selected_crop_name = crop_name
        if self._menu:
            self._menu.dismiss()

    def show_date_picker(self):
        try:
            picker = MDDatePicker()
            picker.bind(on_save=self.on_date_selected)
            picker.open()
        except Exception as e:
            print(f"[PriceHistoryScreen] DatePicker error: {e}")

    def on_date_selected(self, instance, value, date_range):
        self.selected_date = value
        self.selected_date_str = value.strftime("%d %b %Y")

    def load_data(self):
        if not self.selected_crop_id:
            show_snackbar("Please select a crop first.")
            return
        if not self.selected_date:
            show_snackbar("Please select a date first.")
            return

        app = MDApp.get_running_app()
        region_id = app.current_user.get("region_id") if (app and app.current_user) else None
        district = (get_region_district(region_id) if region_id else None) or "Kandy"

        self.ids.actual_date_lbl.text = f"Date: {self.selected_date_str}  •  Crop: {self.selected_crop_name}"

        # 1. Fetch Actual Data
        price = get_price_by_date(self.selected_crop_id, self.selected_date, region_id=region_id)
        prod = get_production_by_date(self.selected_crop_id, self.selected_date, region_id=region_id)

        if price is not None:
            self.ids.actual_price_label.text = f"Rs. {price:,.2f} / kg"
            self.ids.actual_price_label.text_color = (0.15, 0.45, 0.20, 1)
        else:
            self.ids.actual_price_label.text = "No price recorded for this date"
            self.ids.actual_price_label.text_color = (0.6, 0.4, 0.2, 1)

        if prod is not None:
            self.ids.actual_prod_label.text = f"{prod:,.2f} Mt"
            self.ids.actual_prod_label.text_color = (0.15, 0.45, 0.20, 1)
        else:
            self.ids.actual_prod_label.text = "No production recorded for this date"
            self.ids.actual_prod_label.text_color = (0.6, 0.4, 0.2, 1)

        # 2. Predict Next Week
        self.ids.pred_district_lbl.text = f"Forecast Region: {district}  •  Crop: {self.selected_crop_name}"

        curr_p = price if price is not None else 200.0
        pred_price = predict_price(crop=self.selected_crop_name, district=district, current_price=curr_p)
        pred_prod = predict_production(vegetable=self.selected_crop_name, district=district)

        if pred_price is not None:
            self.ids.pred_price_label.text = f"Rs. {pred_price:,.2f} / kg"
        else:
            self.ids.pred_price_label.text = "Prediction unavailable for this crop"

        if pred_prod is not None:
            self.ids.pred_prod_label.text = f"{pred_prod:,.2f} Mt"
        else:
            self.ids.pred_prod_label.text = "Prediction unavailable for this crop"
